dist:     trusty
sudo:     required

language: c

os:
    - linux

compiler:
    - gcc

addons:
  apt:
    packages:
      -Icov
      -valgrind
      -cppcheck
      -make
      -cmake

script:
    # скрипт сборки и тестирования проекта:
    - cd homework_1_5
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./letterTest
    