dist:     trusty
sudo:     required

language: c

os:
    - linux

compiler:
    - gcc

before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"

addons:
  apt:
    packages:
      - lcov
      - valgrind
      - cppcheck
      - make
      - cmake
      - libgtest-dev

script:
    # скрипт сборки и тестирования проекта:
    - sudo apt install cmake
    - sudo apt-get install libgtest-dev
    - sudo apt install gcovr
    - cd homework_2_5
    - cd src
    - clang-format -i -style=WebKit *.c
    - cd ../inc
    - clang-format -i -style=WebKit *.h
    - cd ..
    - cppcheck -q --enable=all --suppress=missingIncludeSystem -I inc/ -I lib/my_static_lib/inc/ -I lib/my_dynamic_lib/inc/ --check-config ./src/ 
    - mkdir build
    - cd build
    - cmake ..
    - scan-build make
    - valgrind --tool=memcheck --leak-check=full ./app
    - ctests
    - gcovr -r ../