dist:     trusty
sudo:     required

language: c

os:
    - linux

compiler:
    - gcc

before_script:
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"

addons:
  apt:
    packages:
      - lcov
      - valgrind
      - cppcheck
      - make
      - cmake
      - libgtest-dev

script:
    # скрипт сборки и тестирования проекта:
      - cd homework_1_5
      - ./install.sh
    # - sudo apt install cmake
    # - sudo apt-get install libgtest-dev
    # - sudo apt install gcovr
    # - cd homework_1_5
    # - cd src
    # - clang-format -i -style=WebKit *.c
    # - clang -g -I../inc -fsanitize=thread *.c
    # - clang -g -I../inc -fsanitize=undefined *.c
    # - clang -g -I../inc -fsanitize=memory *.c
    # - clang -g -I../inc -fsanitize=address *.c
    # - rm a.out
    # - cd ../inc
    # - clang-format -i -style=WebKit *.h
    # - cd ..
    # - cppcheck -q --enable=all ./src
    # - mkdir build
    # - cd build
    # - cmake ..
    # - scan-build make
    # - valgrind --tool=memcheck --leak-check=full ./letterTest
    # - gcovr -r ../ --html coverage --html-details